name: Lint Code Base

on:
  push:
    branches: [ "main", "dev" ] # Adjust the branches as needed
  pull_request:
    branches: [ "main", "dev" ] # Adjust the branches as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Super-Linter
      uses: github/super-linter@v5
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_MARKDOWN: true
        # Add other linters as needed
